
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CardInfo : Luban.BeanBase
{
    public CardInfo(ByteBuf _buf) 
    {
        CardId = _buf.ReadInt();
        Name = _buf.ReadString();
        Cost = _buf.ReadInt();
        Type = _buf.ReadString();
        Rarity = _buf.ReadString();
        Desc = _buf.ReadString();
        IconAddress = _buf.ReadString();
        Price = _buf.ReadInt();
        UpgradeId = _buf.ReadInt();
        SlotAction = _buf.ReadString();
        SlotDistance = _buf.ReadInt();
        Effect1Type = _buf.ReadString();
        Effect1Target = _buf.ReadString();
        Effect1Param1 = _buf.ReadString();
        Effect1Param2 = _buf.ReadString();
        Effect1Condition = _buf.ReadString();
        Effect2Type = _buf.ReadString();
        Effect2Target = _buf.ReadString();
        Effect2Param1 = _buf.ReadString();
        Effect2Param2 = _buf.ReadString();
        Effect2Condition = _buf.ReadString();
        Effect3Type = _buf.ReadString();
        Effect3Target = _buf.ReadString();
        Effect3Param1 = _buf.ReadString();
        Effect3Param2 = _buf.ReadString();
        Effect3Condition = _buf.ReadString();
    }

    public static CardInfo DeserializeCardInfo(ByteBuf _buf)
    {
        return new CardInfo(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int CardId;
    /// <summary>
    /// 卡牌名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 花费<br/>-1表示剩余所有<br/>这个指的是战斗中花费
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 类型<br/>攻击<br/>技能<br/>能力
    /// </summary>
    public readonly string Type;
    /// <summary>
    /// 稀有度<br/>普通<br/>罕见<br/>史诗
    /// </summary>
    public readonly string Rarity;
    /// <summary>
    /// 描述文本<br/>可在此处修改参数然后重新生成，但是改描述需要动代码<br/>词条标记词条名称<br/>词条表已注册名称的词条关联文本会自动查询并展示
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 美术资源加载地址
    /// </summary>
    public readonly string IconAddress;
    /// <summary>
    /// 价格<br/>用于商店消费
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 升级后id
    /// </summary>
    public readonly int UpgradeId;
    public readonly string SlotAction;
    public readonly int SlotDistance;
    public readonly string Effect1Type;
    public readonly string Effect1Target;
    public readonly string Effect1Param1;
    public readonly string Effect1Param2;
    public readonly string Effect1Condition;
    public readonly string Effect2Type;
    public readonly string Effect2Target;
    public readonly string Effect2Param1;
    public readonly string Effect2Param2;
    public readonly string Effect2Condition;
    public readonly string Effect3Type;
    public readonly string Effect3Target;
    public readonly string Effect3Param1;
    public readonly string Effect3Param2;
    public readonly string Effect3Condition;
   
    public const int __ID__ = 56078334;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CardId:" + CardId + ","
        + "Name:" + Name + ","
        + "Cost:" + Cost + ","
        + "Type:" + Type + ","
        + "Rarity:" + Rarity + ","
        + "Desc:" + Desc + ","
        + "IconAddress:" + IconAddress + ","
        + "Price:" + Price + ","
        + "UpgradeId:" + UpgradeId + ","
        + "SlotAction:" + SlotAction + ","
        + "SlotDistance:" + SlotDistance + ","
        + "Effect1Type:" + Effect1Type + ","
        + "Effect1Target:" + Effect1Target + ","
        + "Effect1Param1:" + Effect1Param1 + ","
        + "Effect1Param2:" + Effect1Param2 + ","
        + "Effect1Condition:" + Effect1Condition + ","
        + "Effect2Type:" + Effect2Type + ","
        + "Effect2Target:" + Effect2Target + ","
        + "Effect2Param1:" + Effect2Param1 + ","
        + "Effect2Param2:" + Effect2Param2 + ","
        + "Effect2Condition:" + Effect2Condition + ","
        + "Effect3Type:" + Effect3Type + ","
        + "Effect3Target:" + Effect3Target + ","
        + "Effect3Param1:" + Effect3Param1 + ","
        + "Effect3Param2:" + Effect3Param2 + ","
        + "Effect3Condition:" + Effect3Condition + ","
        + "}";
    }
}
}

