
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EnemyInfo : Luban.BeanBase
{
    public EnemyInfo(ByteBuf _buf) 
    {
        EnemyId = _buf.ReadInt();
        Name = _buf.ReadString();
        HP = _buf.ReadInt();
        Damage = _buf.ReadInt();
        MoveSpeed = _buf.ReadInt();
        Behaviour = _buf.ReadString();
    }

    public static EnemyInfo DeserializeEnemyInfo(ByteBuf _buf)
    {
        return new EnemyInfo(_buf);
    }

    public readonly int EnemyId;
    public readonly string Name;
    public readonly int HP;
    public readonly int Damage;
    public readonly int MoveSpeed;
    public readonly string Behaviour;
   
    public const int __ID__ = 953467958;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "EnemyId:" + EnemyId + ","
        + "Name:" + Name + ","
        + "HP:" + HP + ","
        + "Damage:" + Damage + ","
        + "MoveSpeed:" + MoveSpeed + ","
        + "Behaviour:" + Behaviour + ","
        + "}";
    }
}
}

