
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EnemyGroupInfo : Luban.BeanBase
{
    public EnemyGroupInfo(ByteBuf _buf) 
    {
        GroupId = _buf.ReadInt();
        LevelNum = _buf.ReadString();
        LevelType = _buf.ReadString();
        Content = _buf.ReadString();
        Attribute = _buf.ReadString();
    }

    public static EnemyGroupInfo DeserializeEnemyGroupInfo(ByteBuf _buf)
    {
        return new EnemyGroupInfo(_buf);
    }

    /// <summary>
    /// 组id
    /// </summary>
    public readonly int GroupId;
    /// <summary>
    /// 对应关卡
    /// </summary>
    public readonly string LevelNum;
    /// <summary>
    /// 关卡类型
    /// </summary>
    public readonly string LevelType;
    /// <summary>
    /// 敌人组刷敌
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 关卡特性说明 可选
    /// </summary>
    public readonly string Attribute;
   
    public const int __ID__ = 1632210245;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GroupId:" + GroupId + ","
        + "LevelNum:" + LevelNum + ","
        + "LevelType:" + LevelType + ","
        + "Content:" + Content + ","
        + "Attribute:" + Attribute + ","
        + "}";
    }
}
}

