
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EntryInfo : Luban.BeanBase
{
    public EntryInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Value = _buf.ReadInt();
    }

    public static EntryInfo DeserializeEntryInfo(ByteBuf _buf)
    {
        return new EntryInfo(_buf);
    }

    /// <summary>
    /// 词条id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 词条名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述文本，要在配置层避免自引用或者循环引用<br/>用【】引用描述文本中出现的其他词条
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 数值
    /// </summary>
    public readonly int Value;
   
    public const int __ID__ = 1524267040;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

