
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class FloorClearGoldInfo : Luban.BeanBase
{
    public FloorClearGoldInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Step = _buf.ReadInt();
        Gold = _buf.ReadInt();
    }

    public static FloorClearGoldInfo DeserializeFloorClearGoldInfo(ByteBuf _buf)
    {
        return new FloorClearGoldInfo(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 第几步
    /// </summary>
    public readonly int Step;
    /// <summary>
    /// 金币奖励
    /// </summary>
    public readonly int Gold;
   
    public const int __ID__ = -1649516017;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Step:" + Step + ","
        + "Gold:" + Gold + ","
        + "}";
    }
}
}

