
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class GameBalanceInfo : Luban.BeanBase
{
    public GameBalanceInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        InitialEnergy = _buf.ReadInt();
        CardsPerTurn = _buf.ReadInt();
        MaxStepsPerLayer = _buf.ReadInt();
        MaxLayers = _buf.ReadInt();
        ShortRestHealPercent = _buf.ReadFloat();
        ShortRestMaxCount = _buf.ReadInt();
        WeakMultiplier = _buf.ReadFloat();
        VulnerableMultiplier = _buf.ReadFloat();
    }

    public static GameBalanceInfo DeserializeGameBalanceInfo(ByteBuf _buf)
    {
        return new GameBalanceInfo(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 初始能量
    /// </summary>
    public readonly int InitialEnergy;
    /// <summary>
    /// 每回合抽牌数
    /// </summary>
    public readonly int CardsPerTurn;
    /// <summary>
    /// 每层最大关卡
    /// </summary>
    public readonly int MaxStepsPerLayer;
    /// <summary>
    /// 总共几层
    /// </summary>
    public readonly int MaxLayers;
    /// <summary>
    /// 短休回血比例
    /// </summary>
    public readonly float ShortRestHealPercent;
    /// <summary>
    /// 短休次数上限
    /// </summary>
    public readonly int ShortRestMaxCount;
    /// <summary>
    /// 虚弱伤害倍率
    /// </summary>
    public readonly float WeakMultiplier;
    /// <summary>
    /// 易伤伤害倍率
    /// </summary>
    public readonly float VulnerableMultiplier;
   
    public const int __ID__ = 1565393464;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "InitialEnergy:" + InitialEnergy + ","
        + "CardsPerTurn:" + CardsPerTurn + ","
        + "MaxStepsPerLayer:" + MaxStepsPerLayer + ","
        + "MaxLayers:" + MaxLayers + ","
        + "ShortRestHealPercent:" + ShortRestHealPercent + ","
        + "ShortRestMaxCount:" + ShortRestMaxCount + ","
        + "WeakMultiplier:" + WeakMultiplier + ","
        + "VulnerableMultiplier:" + VulnerableMultiplier + ","
        + "}";
    }
}
}

