
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class PotionInfo : Luban.BeanBase
{
    public PotionInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
        EffectType = _buf.ReadString();
        EffectValue = _buf.ReadInt();
        Address = _buf.ReadString();
    }

    public static PotionInfo DeserializePotionInfo(ByteBuf _buf)
    {
        return new PotionInfo(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly string EffectType;
    /// <summary>
    /// 效果数值
    /// </summary>
    public readonly int EffectValue;
    /// <summary>
    /// 美术资源地址
    /// </summary>
    public readonly string Address;
   
    public const int __ID__ = 682687745;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Price:" + Price + ","
        + "EffectType:" + EffectType + ","
        + "EffectValue:" + EffectValue + ","
        + "Address:" + Address + ","
        + "}";
    }
}
}

