
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class RemoveCardCostInfo : Luban.BeanBase
{
    public RemoveCardCostInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Cost = _buf.ReadInt();
        Increment = _buf.ReadInt();
    }

    public static RemoveCardCostInfo DeserializeRemoveCardCostInfo(ByteBuf _buf)
    {
        return new RemoveCardCostInfo(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 删牌起步价
    /// </summary>
    public readonly int Cost;
    /// <summary>
    /// 每次删牌加价
    /// </summary>
    public readonly int Increment;
   
    public const int __ID__ = 218434575;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Cost:" + Cost + ","
        + "Increment:" + Increment + ","
        + "}";
    }
}
}

