
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ShopCardPackInfo : Luban.BeanBase
{
    public ShopCardPackInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Price = _buf.ReadInt();
        TotalOptions = _buf.ReadInt();
        PickCount = _buf.ReadInt();
        RarityFilter = _buf.ReadString();
        Address = _buf.ReadString();
    }

    public static ShopCardPackInfo DeserializeShopCardPackInfo(ByteBuf _buf)
    {
        return new ShopCardPackInfo(_buf);
    }

    /// <summary>
    /// 唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 卡包名称<br/>
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 卡包描述<br/>需要和后面展示/选择张数保持同步<br/>
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 展示张数
    /// </summary>
    public readonly int TotalOptions;
    /// <summary>
    /// 选择张数
    /// </summary>
    public readonly int PickCount;
    /// <summary>
    /// 稀有度筛选(逗号分隔)
    /// </summary>
    public readonly string RarityFilter;
    /// <summary>
    /// 封面素材资源路径
    /// </summary>
    public readonly string Address;
   
    public const int __ID__ = 1041369037;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Price:" + Price + ","
        + "TotalOptions:" + TotalOptions + ","
        + "PickCount:" + PickCount + ","
        + "RarityFilter:" + RarityFilter + ","
        + "Address:" + Address + ","
        + "}";
    }
}
}

