
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class StartingCardInfo : Luban.BeanBase
{
    public StartingCardInfo(ByteBuf _buf) 
    {
        AutoId = _buf.ReadInt();
        BelongTo = _buf.ReadString();
        CardName = _buf.ReadString();
    }

    public static StartingCardInfo DeserializeStartingCardInfo(ByteBuf _buf)
    {
        return new StartingCardInfo(_buf);
    }

    /// <summary>
    /// 自增id
    /// </summary>
    public readonly int AutoId;
    /// <summary>
    /// 所属武将
    /// </summary>
    public readonly string BelongTo;
    /// <summary>
    /// 卡牌名称
    /// </summary>
    public readonly string CardName;
   
    public const int __ID__ = -707488674;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AutoId:" + AutoId + ","
        + "BelongTo:" + BelongTo + ","
        + "CardName:" + CardName + ","
        + "}";
    }
}
}

