
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbCardInfo TbCardInfo {get; }
    public TbEnemyGroupInfo TbEnemyGroupInfo {get; }
    public TbEnemyInfo TbEnemyInfo {get; }
    public TbEntryInfo TbEntryInfo {get; }
    public TbFloorClearGoldInfo TbFloorClearGoldInfo {get; }
    public TbGameBalanceInfo TbGameBalanceInfo {get; }
    public TbPotionInfo TbPotionInfo {get; }
    public TbRemoveCardCostInfo TbRemoveCardCostInfo {get; }
    public TbShopCardPackInfo TbShopCardPackInfo {get; }
    public TbStartingCardInfo TbStartingCardInfo {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCardInfo = new TbCardInfo(loader("tbcardinfo"));
        TbEnemyGroupInfo = new TbEnemyGroupInfo(loader("tbenemygroupinfo"));
        TbEnemyInfo = new TbEnemyInfo(loader("tbenemyinfo"));
        TbEntryInfo = new TbEntryInfo(loader("tbentryinfo"));
        TbFloorClearGoldInfo = new TbFloorClearGoldInfo(loader("tbfloorcleargoldinfo"));
        TbGameBalanceInfo = new TbGameBalanceInfo(loader("tbgamebalanceinfo"));
        TbPotionInfo = new TbPotionInfo(loader("tbpotioninfo"));
        TbRemoveCardCostInfo = new TbRemoveCardCostInfo(loader("tbremovecardcostinfo"));
        TbShopCardPackInfo = new TbShopCardPackInfo(loader("tbshopcardpackinfo"));
        TbStartingCardInfo = new TbStartingCardInfo(loader("tbstartingcardinfo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCardInfo.ResolveRef(this);
        TbEnemyGroupInfo.ResolveRef(this);
        TbEnemyInfo.ResolveRef(this);
        TbEntryInfo.ResolveRef(this);
        TbFloorClearGoldInfo.ResolveRef(this);
        TbGameBalanceInfo.ResolveRef(this);
        TbPotionInfo.ResolveRef(this);
        TbRemoveCardCostInfo.ResolveRef(this);
        TbShopCardPackInfo.ResolveRef(this);
        TbStartingCardInfo.ResolveRef(this);
    }
}

}
