
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEntryInfo
{
    private readonly System.Collections.Generic.Dictionary<int, EntryInfo> _dataMap;
    private readonly System.Collections.Generic.List<EntryInfo> _dataList;
    
    public TbEntryInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EntryInfo>(n);
        _dataList = new System.Collections.Generic.List<EntryInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EntryInfo _v;
            _v = global::cfg.EntryInfo.DeserializeEntryInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, EntryInfo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EntryInfo> DataList => _dataList;

    public EntryInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EntryInfo Get(int key) => _dataMap[key];
    public EntryInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

