
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEnemyInfo
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyInfo> _dataMap;
    private readonly System.Collections.Generic.List<EnemyInfo> _dataList;
    
    public TbEnemyInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyInfo>(n);
        _dataList = new System.Collections.Generic.List<EnemyInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EnemyInfo _v;
            _v = global::cfg.EnemyInfo.DeserializeEnemyInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.EnemyId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, EnemyInfo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EnemyInfo> DataList => _dataList;

    public EnemyInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EnemyInfo Get(int key) => _dataMap[key];
    public EnemyInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

