
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEnemyGroupInfo
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyGroupInfo> _dataMap;
    private readonly System.Collections.Generic.List<EnemyGroupInfo> _dataList;
    
    public TbEnemyGroupInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyGroupInfo>(n);
        _dataList = new System.Collections.Generic.List<EnemyGroupInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            EnemyGroupInfo _v;
            _v = global::cfg.EnemyGroupInfo.DeserializeEnemyGroupInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.GroupId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, EnemyGroupInfo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<EnemyGroupInfo> DataList => _dataList;

    public EnemyGroupInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public EnemyGroupInfo Get(int key) => _dataMap[key];
    public EnemyGroupInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

