
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbGameBalanceInfo
{
    private readonly System.Collections.Generic.Dictionary<int, GameBalanceInfo> _dataMap;
    private readonly System.Collections.Generic.List<GameBalanceInfo> _dataList;
    
    public TbGameBalanceInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GameBalanceInfo>(n);
        _dataList = new System.Collections.Generic.List<GameBalanceInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GameBalanceInfo _v;
            _v = global::cfg.GameBalanceInfo.DeserializeGameBalanceInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, GameBalanceInfo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<GameBalanceInfo> DataList => _dataList;

    public GameBalanceInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public GameBalanceInfo Get(int key) => _dataMap[key];
    public GameBalanceInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

