
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbRemoveCardCostInfo
{
    private readonly System.Collections.Generic.Dictionary<int, RemoveCardCostInfo> _dataMap;
    private readonly System.Collections.Generic.List<RemoveCardCostInfo> _dataList;
    
    public TbRemoveCardCostInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, RemoveCardCostInfo>(n);
        _dataList = new System.Collections.Generic.List<RemoveCardCostInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            RemoveCardCostInfo _v;
            _v = global::cfg.RemoveCardCostInfo.DeserializeRemoveCardCostInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, RemoveCardCostInfo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<RemoveCardCostInfo> DataList => _dataList;

    public RemoveCardCostInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RemoveCardCostInfo Get(int key) => _dataMap[key];
    public RemoveCardCostInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

