
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbShopCardPackInfo
{
    private readonly System.Collections.Generic.Dictionary<int, ShopCardPackInfo> _dataMap;
    private readonly System.Collections.Generic.List<ShopCardPackInfo> _dataList;
    
    public TbShopCardPackInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ShopCardPackInfo>(n);
        _dataList = new System.Collections.Generic.List<ShopCardPackInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ShopCardPackInfo _v;
            _v = global::cfg.ShopCardPackInfo.DeserializeShopCardPackInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, ShopCardPackInfo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<ShopCardPackInfo> DataList => _dataList;

    public ShopCardPackInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public ShopCardPackInfo Get(int key) => _dataMap[key];
    public ShopCardPackInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

