
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbStartingCardInfo
{
    private readonly System.Collections.Generic.Dictionary<int, StartingCardInfo> _dataMap;
    private readonly System.Collections.Generic.List<StartingCardInfo> _dataList;
    
    public TbStartingCardInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, StartingCardInfo>(n);
        _dataList = new System.Collections.Generic.List<StartingCardInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            StartingCardInfo _v;
            _v = global::cfg.StartingCardInfo.DeserializeStartingCardInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AutoId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, StartingCardInfo> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<StartingCardInfo> DataList => _dataList;

    public StartingCardInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public StartingCardInfo Get(int key) => _dataMap[key];
    public StartingCardInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

